### ISSUE TITLE
Adjust MARC21 mapping for 655: do not map to sourceResource/temporal

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#15]
The options for pulling temporal coverage from the DPLA code are coming from a subfield that is taken out of context (MARC 655$y).  The best field to use would be MARC 648;  if that field is not used by LAPL, the field is optional and should not be included.  The data information should appear as part of a Subject value, (e.g., Group portraits -- 1931 - 1940).  See record:  26904--00000100.

**Comment by aturner** [comment]
Still an issue. See:
https://52.10.100.133/couchdb/_utils/document.html?ucldc/26094--00000100

The value in sourceResource/temporal is being incorrectly taken/mapped from the MARC21 655 (form/genre) field.  Should primarily be taken from MARC21 648 (and the other fields that are by default mapped in the DPLA harvester code for MARC21).
