### ISSUE TITLE
Mapping issue: XTF <subject q="series"> to CouchDB "subject"

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#18]
1) ISSUE

Mapping from this XTF XML element:

 [subject q="series"]

currently targets these CouchDB target elements:

  originalRecord:subject
  sourceRecord:subject

2) PROPOSED CHANGE:

Map incoming [subject q="series"] data to a new CouchDB element: originalRecord:subject-series

3) EXAMPLE:

Source XTF XML record (search for the object with ARK "kt029016nn"):
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt138nc5cn&docsPerPage=200

CouchDB record:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn

**Comment by mredar** [comment]
So you want the subject records with q="series" to be suppressed in the sourceResource record

**Comment by aturner** [comment]
I think we should preserve it in the originalRecord section (suggest we map it to a field named something like: subject-series).  For our own internal purposes, we might want to have that handy.

But *not* carry this forward all the way through to sourceRecord, for ultimately exposing to DPLA.

**Comment by aturner** [comment]
Mark, I think we can safely close it -- I've also accepted the related story in Pivotal #https://www.pivotaltracker.com/story/show/86155534
