### ISSUE TITLE
Mapping issue: XTF <format q="x"> to CouchDB "format"

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#20]
1) ISSUE

Mapping from this XTF XML element:

 [format q="x"]

currently targets these CouchDB target elements:

  originalRecord:format
  sourceRecord:format

2) PROPOSED CHANGE:

Map incoming [format q="x"] data to a new CouchDB element: originalRecord:format-additional

3) EXAMPLE:

Source XTF XML record (search for the object with ARK "kt029016nn"):
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt138nc5cn&docsPerPage=200

CouchDB record:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn

**Comment by mredar** [comment]
Modify the OAC xml fetcher to save the values as a dictionary with 'attrib' and 'text' for each element.
Can then suppress various fields based on value of attrib.

Will suppress format, attrib 'q'=='x'

**Comment by aturner** [comment]
Cool!

**Comment by aturner** [comment]
Mark, I think we can safely close it -- I've also accepted the related story in Pivotal #https://www.pivotaltracker.com/story/show/86155534
