### ISSUE TITLE
Data cleanup: Develop option to selectively suppress data (e.g., <publisher>) from coming through to sourceResource fields, by a particular collection

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#21]
1) ISSUE

San Bernardino Public Library's "Historical Treasures" collection (10046) contains problematic data in the XTF <publisher> field:

              <publisher>San Bernadino Public Library</publisher>
              <publisher>San Bernardino Public Library</publisher>
              <publisher>&lt;a href="http://sbpl.org/shades_0346.jpg"&gt;Click here for full size image.&lt;/a&gt;&lt;br/&gt;
        &lt;img src=http://sbpl.org/shades_0346.gif border=0&gt;</publisher>
               <publisher>:</publisher>

None of this data is not displayed in Calisphere presentation of the metadata.

However, in other Calisphere metadata cases (looking at other random samples, from other collections), the [publisher] data looks good.

2) PROPOSED CHANGE:

Incorporate a toggle in the harvesting code to selectively suppress a XTF data element, from coming through to CouchDB.  In the case of this particular collection, suppress [publisher].  Or alternatively have it come through to originalRecord -- but prevent it from going through to sourceResource.

See also GitHub #51.

3) EXAMPLE:

Source XTF XML record (search for the object with ARK "kt029016nn"):
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt138nc5cn&docsPerPage=200

CouchDB record:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn

**Comment by aturner** [comment]
Another example: from this particular collection, we'd want to selectively suppress "spatial" data from coming through in sourceResource (which comes from originalRecord "coverage").  The collection consistently has ARK values in that particular data field. 

Display of data values in this field, from this collection.
https://54.84.142.143/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2219405%22&field=originalRecord.coverage&limit=500

Example object:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/19405--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt967nd01n

**Comment by mredar** [comment]
These are 2 separate cases, the one directly above is just suppressing a particular value. The other case is a particular field in a particular collection. I made a change to suppress "coverage" values that match 'ark:', pretty safe bet that is not spatial data.

This is going to be easier to nail on a case-by-case basis. The problem with a generic suppress is the syntax of the call, how to represent dictionary fields vs array fields and then filters for content?

Maybe a content_filter regex would be not to bad to support  -- if the string field matches the regex then suppress.

the index of a field is  stickier issue.

**Comment by aturner** [comment]
So0rt of related to #51 (but less critical, in this particular case of wanting to suppress Publisher info.)
