### ISSUE TITLE
Incorrect algorithm for dpla:sourceResource "isShownBy" for LAPL MARC records

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#25]
After developing a better understanding of what this field is, will need to change the algorithm for this value.  From DPLA, the definition for this value is:  Unambiguous URL to the DPLA content preview image.  The algorithm for the "isShownAt" value gets you to the item metadata record, and then clicking on the jpg file URL gets you to the higher resolution preview image.  There is also a thumbnail image on the item metadata record.  Perhaps by appending the jpg value to the algorithm for "isShownAt" will get you to the fuller image.  Didn't work in the web view.  Adrian says you know how to get this, Mark.  

See 26094--00058528 for an example which has the following jpg URL in the MARC 856 subfield u field:  http://jpg2.lapl.org/pics48/00058528.jpg .

**Comment by aturner** [comment]
Nancy -- just for clarification.  In this example LAPL MARC21 record:

https://54.84.142.143/couchdb/_utils/document.html?ucldc/26094--00058528

The "IsShownBy" URL is good.  That's what we want -- i.e., a URL reference that resolves to an actual image file.  It's basically what's in their 856 field.

I think what we need is to incorporate some logic into the MARC21 ingest feed for LAPL, where we can derive something for "isShownAt".  And what we want for that is a URL that shows the MARC21 record and image in LAPL's platform, where the object is in its full information context.  Here's what we came up wwith for that, as the logic: grab the last 5 (?) digits of 910 $a, and append to this base URL:

http://photos.lapl.org/carlweb/jsp/DoSearch?index=z&databaseID=968&count=10&initialsearch=true&terms=

**Comment by njhoebel** [comment]
That's what I suggested for the isShownAt algorithm.  It gets you to the item metadata record.

**Comment by aturner** [comment]
Cool.  From the issue description, it sounds like there is a problem with the URL that's coming through to "isShownBy" -- but I think the URL that we're getting is good.

**Comment by njhoebel** [comment]
You get to the same place for the isShownBy with that algorithm, but you don't get to the actual image file until you click on the "Click on this to get the image" URL in this metadata record.  Then, you get to the image.  It is not transparent how you get to the image at the "Click on this image..." where you actually see the higher resolution image (than the thumbnail in the item metadata record.).  DPLA may be ok with either;  hard to tell from what Gretchen said to us in the email message that I quoted.

**Comment by aturner** [comment]
I'm not sure I understand. For "isShownBy", we just need a URL -- or need to compute a URL -- that resolves to an actual file -- which DPLA (and we) can use to generate something like a thumbnail image, for search/browse results.  In LAPL's case, the URL we're getting in the 856 seems like it's spot-on for this purpose.  So it seems like we don't need to modify the mapping for what's coming through from 856 and getting dumped into "isShownBy".

For "isShownAt", we need a URL -- or need to compute a URL -- that resolves to a public display/view of the metadata record and related image or files, within its native habitat and context.  In LAPL's case, there's nothing immediate in the MARC record that gets us this -- so we need to incorporate that algorithm/logic into the LAPL MARC harvest process, to compute that URL.

**Comment by mredar** [comment]
I'm going to close this issue. The isShownBy is what we want, the current isShownAt is not correct but used the same 856 value just to have something there

**Comment by njhoebel** [comment]
Use of the 856 field for this value works by independent testing in another browser when it is correct in the record.  Sometimes it doesn't work, apparently when the URL has changed on the website,but not in the metadata record.  The errors will need to be corrected by LAPL if they can be discovered easily by us or by DPLA.
