### ISSUE TITLE
Collection Registry field addition: "Type"

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#26]
I think we may need to add a "Type" data field in the Collection Registry, tied to the DCMI Type vocabulary, to globally supply one of those data values for a given collection -- if that data isn't present in the source metadata.

DPLA requires Type; and we (CDL) will also need it.

For example, see the LAPL CONTENTdm-harvested records -- no Type data is available in the source:

https://54.84.142.143/couchdb/_utils/document.html?ucldc/26097--oai%3A173.196.26.156%3Amovie%2F0

**Comment by mredar** [comment]
Just a thought, would we use the "Nuxeo Formats" for this, a bit funky but might work.

**Comment by aturner** [comment]
In Nuxeo, we have the UCLDC metadata scheme which supports "Type" -- tied to the DCMI type vocabulary.  And for everything coming out of Calisphere, it looks like we have a pretty good consistent piece of metadata that corresponds to the DCMI type vocab.

**Comment by aturner** [comment]
From the DCMI Type Vocabulary list:

 
    Dataset
    Image
    Software
    Sound
    Text

**Comment by aturner** [comment]
See also GitHub #48

**Comment by aturner** [comment]
Mark, closeable - yes?

**Comment by mredar** [comment]
But we need to fill in the collections with appropriate types

**Comment by aturner** [comment]
The process is hooked up, though, right?  If we set the Type value in the Registry, it *should* now flow into the metadata records that are harvested.

**Comment by mredar** [comment]
yep, again the problem with the collections already run with long rights statement and copyright unknown is that fixing them is a bit of custom process. started last friday but is more involved than expected.

**Comment by aturner** [comment]
Gotcha, thanks.  Sounds like we can close this, as the Type values will be prospectively added to metadata (if set in the Registry); but we still have the legacy harvested stuff, and the issue of fixing those records.  I definitely like the idea of honing in on the harvesting infrastructure as a "theme" and macro-priority -- so we can ultimately just re-run a new harvest of everything, to pick up all of the changes.

**Comment by njhoebel** [comment]
Not sure what this means (Adrian's comment above);  will put this on the agenda to talk about at our meeting today.
