### ISSUE TITLE
Harvesting failure: only some object metadata is coming through to CouchDB for a particular collection (Calisphere/XTF)

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#28]
Mark -- here's a good example of a collection, where only a few objects got harvested into CouchDB.

It's the "Coronado Local History Photograph and Map Collection", Django ID #5112.

1) The collection in OAC -- there are 197 objects:
http://www.oac.cdlib.org/items/findaid/ark:/13030/kt4n39r09j/

2) Here's the URL in Django to the complete results set:
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt4n39r09j

3) And here's what's in CouchDB -- only 3 objects:
https://54.84.142.143/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%225112%22&field=originalRecord.subject&limit=100

**Comment by aturner** [comment]
Mark,

Another case:

From the Citrus College's "Citrus College Archive Collection", Django ID #4438.

1) The collection in OAC -- there are 219 objects:
http://www.oac.cdlib.org/items/findaid/ark:/13030/c8v40sx8/

2) Here's the URL in Django to the complete results set:
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/c8v40sx8&docsPerPage=219

3) And here's what's in CouchDB -- only 84 objects:
https://54.84.142.143/couchdb/ucldc/_design/all_provider_docs/_view/by_provider_name_count?group=true&key=%224438%22

**Comment by aturner** [comment]
Mark -- another one.  Not sure if this has been fixed, as part of https://www.pivotaltracker.com/story/show/86654570 (and we just need to re-run the harvest completely, for all of the objects to come through).  Reporting this in case if not:

1) The collection in OAC -- 1,348 objects:
http://www.oac.cdlib.org/view?docId=tf0779n3nm;developer=local;style=oac4;doc.view=items

2) Here's the URL in Django to the results set:
dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/tf0779n3nm&docsPerPage=2000

3) And here's what's in CouchDB -- only 4 objects:
https://54.84.142.143/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%2218804%22&field=originalRecord.title&limit=500

**Comment by mredar** [comment]
All of these examples have been fixed by recent harvest run.
