### ISSUE TITLE
Adjust MARC21 mapping for 651 $a (weigh it/prefer over MARC21 655 $z; exclude the latter?) to sourceResource/spatial

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#29]
This will probably apply to any collections with MARC21 metadata.  For dc:spatial, the DPLA code (according to Mark's reading as documented on the Master spreadsheet) calls for pulling the values from the 650 subfield z fields, and from the 651 subfield a field.  For most specificity, preference should be given to the 651 subfield a field as it will have all the information elements to create the geographic information that DPLA needs.  See, for example, the LAPL MARC collection, 26094--00003281 in the dc:spatial field which in pulling from MARC 651 subfield a provides the values:   "Panorama City (Los Angeles, Calif.)".

**Comment by mredar** [comment]
Is there any problem with leaving the less specific data in the output field? Definitely want to remove duplicates but I don't believe it will hurt to have multiple values for the spatial field.

**Comment by njhoebel** [comment]
I guess not.  Depends upon the DPLA code and what they're actually looking for, but they can say that too if they want when they look at our feeds...

**Comment by njhoebel** [comment]
Per a discussion of this topic on 28 January 2015, this should be put on the enhancement list at a later date, as there are tools (per Mark) that can be used to identify, validate, and insert geographic coordinates or codes into a record, but will not be possible to do until later in the game.
