### ISSUE TITLE
`url_item` should be a web page

### ISSUE THREAD

**Issue by tingletech** [ucldc/harvester#30]
I don't think we should have a link to an image at `url_item`

when we have a "`url_item":` like 
`"http://jpg3.lapl.org/pics18/00028946.jpg"`
 
I think we want a way to link to the OPACs HTML page -- or we need to host the page.

![screen shot 2015-01-14 at 7 35 36 pm](https://cloud.githubusercontent.com/assets/227374/5752153/9c82e3c4-9c24-11e4-8c46-7c5e51ffc29a.png)

Also, the "url_item = jpg" ones all seem to be missing the md5 stuff

**Comment by mredar** [comment]
this is due to isShownAt being bogus see issue #24

**Comment by mredar** [comment]
pushed solr index with this fix
