### ISSUE TITLE
Harvesting failure: no objects coming through to CouchDB for a given collection (Calisphere/XTF)

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#31]
I'm seeing a lot of cases where the harvesting failed for a collection -- and creating this ticket to formally add an example to the mix.

This collection is the Glendale Library's "Collection of historic photographs and documents related to Leslie C. Brand", Django ID #4711.

1) The collection in OAC -- there are 225 objects:
http://www.oac.cdlib.org/items/findaid/ark:/13030/kt6n39q5wx/

2) Here's the URL in Django to the complete results set:
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt6n39q5wx&docsPerPage=225

No results in CouchDB for this particular collection:

https://54.84.142.143/couchdb/ucldc/_design/all_provider_docs/_list/has_field_value/by_provider_name_wdoc?key=%224711%22&field=originalRecord.subject&limit=100

**Comment by mredar** [comment]
Take a look at this now Adrian, successfully harvested this. WIll look at the partial harvest next
