### ISSUE TITLE
dc:creator field not showing up in couchDB from LAPL MARC 

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#32]
The dc:creator value should be coming in from the MARC 100, 110 or 111 fields and is not showing up.  See 26094--00103111 record as an example.

**Comment by njhoebel** [comment]
Another example record is:  26094--LAPL00058828.

**Comment by mredar** [comment]
What subfields should the data come from, it is in the "a" field for the samples

**Comment by njhoebel** [comment]
Oops, should have specified it in the note, sorry!  Would be coming from the 1xx fields (100, 110, 111) and should be mostly in subfield a, but can probably use all subfields that are present (in case there's a title, date associated, etc.).

**Comment by mredar** [comment]
Sounds good, thats how my first fix is implemented.
Pushing code and running today so tomorrow we should have the LAPL issues fixed.
