### ISSUE TITLE
for dc:subject, LAPL MARC 655$a, Subject heading of form/genre is used incorrectly in sourceRecord -- TB discussed with DPLA

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#33]
CDL has discussed this issue and decided to let this kind of information come through even though it is technically incorrect per the rules for the field.  
For example:
02694-00045439 has a value of:  "a": "Los Angeles Evening Herald and Express photographs." for the 655 field with indicator 2 = "2": "gmgpc which is the code for the source of the term (The Thesaurus for Graphic Materials).  A search for this field fails to find the term / phrase. [ It should be something like Photographs.]  

Because this kind of info would still be valuable to include as descriptive info, we've decided to keep it in, but raise it / notify DPLA that is the case.

**Comment by njhoebel** [comment]
We should also bring this up to DPLA as well as another example of our letting inappropriate (per the MARC rules) data into the feed.  The MARC fields in question in the LAPL MARC MD are 530, 541, and 590.

**Comment by aturner** [comment]
Nancy -- have you come across any LAPL or SFPL MARC21 records, where they have 655 data that's correctly applied (i.e., using content/cataloging standards), and you're seeing true form/genre data values like "Photographic prints"?  If so, where are they winding up within CouchDB?  

Per the DPLA MAP (v. 4), I think we should carve out a CouchDB field that's named something like "specificTypeGenre" (for "Specific Type / Genre" -- which has the analog edm:hasType), and put the 655 data there.

**Comment by njhoebel** [comment]
Regarding your question of whether I've seen any LAPL or SFPL MARC21 records with the "correct" values for 655, no I haven't seen any (although we only have the 50 record sample from SFPL, of course).   There are genre type values in the LAPL MOVIE POSTER collection (CONTENTdm), but they are included under dc:format. The value that they've consistently included is:  "Motion picture posters; Lithographs".  So, there's probably no need for this from the POV of these collections.
