### ISSUE TITLE
Mapping refinement: originalRecord:relation:0 -> sourceRecord:collection:collection-url

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#34]
The following field/subfield in originalRecord:

	relation
		0
		

... should be analogous to the following new field/subfield in sourceResource.  This will require estabilishing the new subfield named "collection-url":

	collection
		collection-url

EXAMPLE DATA VALUE
http://www.oac.cdlib.org/findaid/ark:/13030/kt138nc5cn

EXAMPLE RECORD:
https://54.84.142.143/couchdb/_utils/document.html?ucldc_samples_from_10046_2014-12-18/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn

**Comment by mredar** [comment]
Leaving this for now, think we need to think more about what the old OAC urls mean in our new system.

**Comment by aturner** [comment]
Is there a location in the sourceResource record where DPLA could consistently and predictably obtain the finding aid URL?

**Comment by aturner** [comment]
collection/url_oac now in CouchDB; populated with finding aid URL if available
