### ISSUE TITLE
Mapping refinement: originalRecord:repository:0:name -> sourceRecord:dataProvider

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#37]
The following field/subfield in originalRecord:

	repository
    		0   
       	 		name

... should be analogous to the following new field/subfield in sourceResource. This will require estabilishing the new field named "dataProvider" (see GitHub #36).  Can we append the repository information to the campus name, starting with a comma?:

	dataProvider

Assuming we move forward with the above: note that there is an existing "dataProvider" table/field in CouchDB (with 0-n subfields) -- which appears as a primary field type (see 8th row at https://54.84.142.143/couchdb/_utils/document.html?ucldc_samples_from_10046_2014-12-18/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn).  I think this data field really should be in the sourceResource section -- so could we safely hose it, as a primary field type?

EXAMPLE DATA VALUE
San Bernardino Public Library
UC Berkeley, Bancroft Library 

EXAMPLE RECORDS:
https://54.84.142.143/couchdb/_utils/document.html?ucldc_samples_from_10046_2014-12-18/10046--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt029016nn

https://54.84.142.143/couchdb/_utils/document.html?ucldc/23065--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt096n99pb

**Comment by mredar** [comment]
For both this & #36, from this http://dp.la/info/developers/codex/responses/object-structure/
the data provider is in the correct spot. But we should probably put a single value of the campus & repo name concatenated in some way.

**Comment by aturner** [comment]
Cool, re: leaving dataProvider at the root level (and not subsuming it as a field within sourceResource).  But totally agree that we should concatenate campus and repository name -- a la:

[campus], [repository name]

**Comment by aturner** [comment]
Adding example record for UCB, where we want the syntax for dataProvider to be:  [campus], [repository]

https://54.84.142.143/couchdb/_utils/document.html?ucldc/23065--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt096n99pb
