### ISSUE TITLE
Mapping double-check: originalRecord:[alternative title] -> sourceRecord:alternativeTitle

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#38]
To confirm if we are getting any metadata from the XTF-based XML, which is mapped to the DC equivalent of dcterms:alternative (alternative title).

This data should get mapped all the way through to the following new sourceRecord field/subfield in CouchDB:

	alternativeTitle

**Comment by mredar** [comment]
any samples that have an alternative title in the OAC search results?

**Comment by mredar** [comment]
This is not currently getting pulled forward.

**Comment by aturner** [comment]
I couldn't find anything in the wild, as far as a sample.

**Comment by aturner** [comment]
Found an example of an object with an alternative title.  It looks like the <title q="alternative"> data is getting passed through to originalRecord:title:1 (and onwards to sourceResource:title:1) -- and not to a more granular, and proposed new "alternativeTitle" field.

1) Calisphere view of object:
http://content.cdlib.org/ark:/13030/hb1p3001cj/?layout=metadata&brand=calisphere

2) CouchDB record for object:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/143--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fhb1p3001cj

3) From XTF XML:
<docHit rank="26" path="cdl:13030/cj/hb1p3001cj/hb1p3001cj.mets.xml" score="100"
                 totalHits="0">
            <meta>
               <title>"Will It Come to This?"</title>
               <title q="alternative">
          [Chinese man sitting on top of dynamite and white labor, poised to explode brick wall of Public Opinion]</title>
    ...
            </meta>
         </docHit>
