### ISSUE TITLE
Mapping refinement: sourceRecord:Provider ("California Digital Library")

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#43]
Establish a new field in sourceRecord, labeled "Provider".  This field should have the constant data value: "California Digital Library".  (Formal name of CDL as a DPLA Content Hub)

**Comment by mredar** [comment]
I think the provider field is a direct property of the object, it doesn't go under the "sourceResource" but is directly under the object like the id property.
Also, DPLA will actually ignore this as they will fill in  this value. We can repurpose it or not use it at all.

In our context, provider should probably be the repository and campus?

**Comment by aturner** [comment]
In our context (just as with DPLA), I think we should use "dataProvider" for the institution that's contributing stuff to us (and to DPLA).  I think we should establish a separate "Provider" field that globally indicates "California Digital Library" as the uber aggregator.
