### ISSUE TITLE
Mapping double-check: originalRecord:[extent] -> sourceRecord:extent

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#45]
To confirm if we are getting any metadata from the XTF-based XML, which is mapped to the DC equivalent of dcterms:extent (assuming we're not dumbing it down to dc:format).

If we *are* storing specific dcterms:extent information in XTF, this data should get mapped all the way through to the following new sourceRecord field/subfield in CouchDB:

	extent

**Comment by mredar** [comment]
This looks like it is in the code. Need to find a record to check.
