### ISSUE TITLE
Detect if Type or Rights Status/Statement have null values; if no value, then apply data from the Collection Registry

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#48]
Most (or a vast number?) of early EAD-extracted objects lack rights metadata -- and are good examples/use cases for this.  This includes tons of stuff from UCB Bancroft, as well as early MOAC objects.  An example:

1) CouchDB object:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/12531--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Ftf0000061f

2) Calisphere view of object:
http://content.cdlib.org/ark:/13030/tf0000061f/?layout=metadata&brand=calisphere

I.e., if objects have null/missing metadata in sourceResource:rights, then we should supply some default boilerplate statement that indicates something along the lines of "contact the contributing institution for information about the copyright status of this item".  We could confer with Katie on proposed verbiage.

**Comment by njhoebel** [comment]
See related issue #64 which includes a listing of all the required values for DPLA & CDL in the explanation section.

**Comment by aturner** [comment]
I think we can close this one, too.
