### ISSUE TITLE
Data cleanup: Develop option to selectively suppress copyrighted transcriptions data (in <description>) from coming through to sourceResource fields, by a particular collection

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#51]
1) ISSUES

We have source metadata records, where transcription information (with underlying rights info., which we can't share with DPLA) is included in a Description field that's mapped to XTF [description], within a second instance of that element.  

2) PROPOSED CHANGE:

Incorporate a toggle in the harvesting code to selectively suppresss the second instance of [description] in the originalRecord, from appearing within sourceResource.  See also GitHub #21

3) EXAMPLES:

Source XTF XML record (search for the object with ARK "c80g3j03"):
http://dsc.cdlib.org/search?facet=type-tab&style=cui&raw=1&relation=ark:/13030/kt538nf1bb&docsPerPage=200

CouchDB record:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/15486--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fc80g3j03

**Comment by mredar** [comment]
Going to handle this by modifying the mapper for the particular collection in question to not pull the data forward.
Will do this for the collection listed above, create a special oac_dc_mapper that suppress the 2nd item in the description field

**Comment by aturner** [comment]
Sort of related to GitHub #21?

**Comment by aturner** [comment]
These are the *two* collections I could identify (all LHDRP-based), where we have transcriptions in the metadata -- which need to be suppressed from going to DPLA.  The transcriptions consistently appear in the second instance of [description] in the originalRecord:


1) Nance (Afton) Dill Papers (collection ID #15486)

Registry entry: https://registry.cdlib.org/admin/library_collection/collection/15486/

Calisphere view: http://content.cdlib.org/search?facet=type-tab;brand=calisphere;style=cui;institution=Japanese+American+National+Museum;collection-title=Afton+Dill+Nance+Papers


2) Workman Family Papers (collection ID #25043)

Registry entry: https://registry.cdlib.org/admin/library_collection/collection/25043/

Calisphere view: http://content.cdlib.org/search?facet=type-tab;brand=calisphere;style=cui;institution=Loyola+Marymount+University%2C+Department+of+Archives+and+Special+Collections%2C+William+H.+Hannon+Library;collection-title=Workman+Family+Papers

**Comment by mredar** [comment]
see https://54.84.142.143/couchdb/_utils/document.html?ucldc/25043--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt358035fj

&

https://54.84.142.143/couchdb/_utils/document.html?ucldc/15486--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fc80v8d8q

use a different mapper (oac_dc_mapper_suppres_desc_2 ) for mapping these collections.
