### ISSUE TITLE
Data cleanup: provide collection-based enhancement option to separate out data values, based on a delimiter such as a semicolon (e.g., each dc:subject value for UCSC OAI-PMH collections))

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#54]
For example, see the dc:subject values for LAPL CONTENTdm Movie Poster collection which are all concatenated together and separated by semi-colons within a single subject entry rather than being displayed as separate subject values.  This may be important for purposes of assigning URIs to each subject later by DPLA and/or CDL.  

See:  26097--oai:173.196.26.156:movie/17.

**Comment by aturner** [comment]
Another example:

https://54.84.142.143/couchdb/_utils/document.html?ucldc/19405--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt967nd01n

**Comment by aturner** [comment]
Example object from UCSC:

https://54.84.142.143/couchdb/_utils/document.html?ucldc/127--oai%3Acdm16019.contentdm.oclc.org%3Ap265101coll25%2F100

**Comment by aturner** [comment]
We should use DPLA's code for this
