### ISSUE TITLE
isShownAt value not coming through for Calisphere/XTF-harvested metadata record

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#56]
isShownAt value (ARK URL) is not coming through for some Calisphere/XTF-harvested metadata.  Shows up as "null"

Example below (will try to find others):

EXAMPLE:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/528--http%3A%2F%2Fark.cdlib.org%2Fark%3A%2F13030%2Fkt0000098v

**Comment by mredar** [comment]
this query will show how many isShownAt fields are missing.
https://54.84.142.143/couchdb/ucldc/_design/qa_reports/_view/isShownAt_value?limit=100&group_level=2&start_key=%5B%22__MISSING__%22%5D

The one above looks fixed.

The isShownBy query
https://54.84.142.143/couchdb/ucldc/_design/qa_reports/_view/isShownBy_value?limit=100&group_level=2&start_key=%5B%22__MISSING__%22%5D

will tell us if there should be an image in s3
