### ISSUE TITLE
Harvesting issue: some Calisphere collections are missing from the Collection Registry

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#58]
1) CSU East Bay.  There are 5 listed in Calisphere:

http://www.calisphere.universityofcalifornia.edu/institutions/California+State+University,+East+Bay+University+Archives/

But only 1 from the above in the Collection Registry:

https://registry.cdlib.org/admin/library_collection/collection/?q=california+state+university+east

2) UCI Mitsuye Yamada Papers.  Listed in Calisphere:

http://www.calisphere.universityofcalifornia.edu/institutions/UC+Irvine::Special+Collections/

But not set up for harvesting in the Collection Registry:

https://registry.cdlib.org/admin/library_collection/collection/25195/

**Comment by mredar** [comment]
At some point, need to look at the syncing code. But for now, if we can find an ark for the collections above that would be good.

Then we need to add the unlisted collections into the Registry and try & populate the harvest info. Let's sort it at the meeting

**Comment by aturner** [comment]
We need to come up with a procedure/methodology for human QA'ing of this -- check Calisphere list of collections vis-a-vis Collection Registry, update the latter...
