### ISSUE TITLE
Flag when DPLA required values do not appear in full record including harvesting code insertions  - generic

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#64]
Requested from MD / QA discussion of 28 january 2015:
Required DPLA values are:
- dc:title
- dc:rights (dpla:sourceResource) at least this one
- dc:rights (edm:WebResource) 
- dc:type (required by CDL; recommended by DPLA)
- dpla:originalRecord 
- edm:aggregatedCHO (to be derived by DPLA) -- so maybe we don't have to worry about it??
- edm:isShownAt
- edm:object (aka isShownBy)
- edm:provider (should be California Digital Library)

**Comment by aturner** [comment]
Clarifying this GitHub issue: is the idea that the "flag" would be realized in the form of some type of report, that's generated at the point of harvesting?  And we could then use that as part of the QA process, and to know when the data needs remediation?
