### ISSUE TITLE
Adjust MARC21 010 mapping for SFPL: map to sourceResource:identifier

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#70]
This value is present in the original record; is a recommended field for DPLA, but is the primary PHOTO ID for SFPL, so important to include.  See:
26095--AAA-9929
and 
26095--AAA-9172

**Comment by aturner** [comment]
MARC21 010 is used for LC control numbers -- I think SFPL is technically not really using the field correctly, if they're using it for their local photo ID.  That said, they're displaying this info. on their local system -- and it's good information for end users:

SFPL sample:
http://sflib1.sfpl.org:82/record=b1004989

CouchDB sample:
https://52.10.100.133/couchdb/_utils/document.html?ucldc/26095--AAA-9929

**Comment by aturner** [comment]
https://www.pivotaltracker.com/story/show/88831010
