### ISSUE TITLE
Mapping issue for XTF tags for subject:  not showing up in sourceResource when it appears in original record.

### ISSUE THREAD

**Issue by njhoebel** [ucldc/harvester#75]
Mapped to:  /crossQueryResult/facet/group/docHit/meta/subject, the sourceResource dc:subject is now showing up.  See:  16703--http://ark.cdlib.org/ar:/13030/tf000005bm

and 17070--http://ark.cdlib.org/ark:/13030/tf00000551

**Comment by njhoebel** [comment]
This is not true for every collection.  For example, see:  17170--http://ark.cdlib.org/ark:/13030/kt3z09q396  where subjects do show up, but from the facet-subject tag rather than the /meta/subject tag as is the case with the two collections above.  Can't see any difference except the metadata for those two collections above are sparse and in each case what is in the subject is also the collection title, (although not the same collection title that is in the collection information pulled from the Collection Registry.)

**Comment by njhoebel** [comment]
Note that sometimes when there is both a /meta/subject tag and a facet-subject tag, the values do not always match.  For example, in this record:  17170--http://ark.cdlib.org/ark:/13030/kt3z09q396 there is a subject in the /meta/subject tag that is not in the facet-subject tag -- which also is a non-Collection Registry version of a collection title.  Perhaps we could take both, then run the de-duper over them so that only the unique values will appear?

**Comment by aturner** [comment]
Regarding the first issue noted: this is intentional -- we don't want the series-related information (which was originally from the finding aid) to come through all the way to the sourceResource record, in the "Subject" field.  GitHub #https://github.com/ucldc/harvester/issues/18

**Comment by njhoebel** [comment]
So should it be mapped to facet-subject then which doesn't seem to have the series info in it?  See the example 17170--http://ark.cdlib.org/ark:/13030/kt3z09q396.

**Comment by aturner** [comment]
Anything in originalRecord in the Subject element, which has the attribute "series", should not get mapped forward to sourceResource

**Comment by njhoebel** [comment]
OK, I've added that restriction in the Master spreadsheet, and will delete this issue.

**Comment by aturner** [comment]
Nancy, I'm not sure I follow.  With the subject mappings from XTF, we should only be carrying forward data from /crossQueryResult/facet/group/docHit/meta/subject -- and that data should ultimately be mapped forward all the way to sourceResource "Subject" in CouchDB.  The exception are subject headings in XTF that are encoded as <subject q="series"> -- those should be preserved in originalRecord, but should not get mapped all the way forward to sourceResource "Subject" in CouchDB.
