### ISSUE TITLE
SFPL images with two 856 URLs: the first URL (with link to the image file) didn't get picked up for isShownAt, so broken thumbs in DPLA

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#78]
CouchDB record:
https://52.11.194.40/couchdb/_utils/document.html?ucldc/26095--GLC-0108

DPLA view:
http://dp.la/item/94c4c8369d0322d01fd8d4cd8a7224f0?back_uri=http%3A%2F%2Fdp.la%2Fsearch%3Futf8%3D%25E2%259C%2593%26q%3DHarvey%2BMilk%2Bholding%2Bgoat

**Comment by tingletech** [comment]
why is this high priority?
