### ISSUE TITLE
UCSF metadata harvesting mapping modifications

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#81]
Suggest that we re-map <brd>: Brands to sourceResource:subject (instead of sourceResource:description).

That said, there's a lot of data going into sourceResource:subject -- making for some potentially very extensive records (e.g., https://54.84.142.143/couchdb/_utils/document.html?ucldc/26100--aaa13j00 ).  The current mappings are documented in cell N24 at https://docs.google.com/spreadsheets/d/1u2RE9PD0N9GkLQTFNJy3HiH9N5IbKDG52HjJ6JomC9I/edit#gid=265758929 .

To trim things down, suggested approach is the following:  

1) Keep mappings from these elements to sourceResource:subject
<brd>: Brands
<men>: Mentioned
<meno>: Organizations mentioned
<org>: Organizations mentioned
<menp>: Persons mentioned
<per>: Persons mentioned

1) Exclude mappings from these elements to sourceResource:subject
<cc>: Copied
<cco>: Organizations copied
<ccp>: Person copied
<rc>: Recipients
<rco>: Organization recipients
<rcp>: Person recipients

**Comment by mredar** [comment]
Implemented in code, need to run. Will run all collections to stage once UCSD & UCI modifications in place
