### ISSUE TITLE
UCSB MARCXML records: determine the extent of records that have non-UCSB URLs

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#82]
Metadata looks like it carried over fine.

I noticed some records in CouchDB that have 856 URLs that are non-UCSB -- for example an object from Syracuse in NY: "http://digilib.syr.edu/u?/cylinder,364"

https://54.84.142.143/couchdb/_utils/document.html?ucldc/113--http%3A%2F%2Fdigilib.syr.edu%2Fu%3F%2Fcylinder%2C364

My understanding is that UCSB-owned digitized cylinder recordings should only be provided in the MARCXML feed. I tried to retrieve the full snapshot of MARCXML records from the URL they provided:

http://pegasus.library.ucsb.edu:5661/sba01pub?version=1.1&operation=searchRetrieve&query=dc.format=wd&maximumRecords=20000

... but don't see any of those Syracuse objects in the records I successfully downloaded. Reality check, are you seeing the Syracuse stuff in their feed? If not, how did that first record get into CouchDB?

**Comment by mredar** [comment]
Ana at UCSB determined that there were 6 syracuse records in the feed and will try and filter.
There are some records that have both syracuse & UCSB URLs, I changed mapping to only put ucsb matching URLs into isShownAt/By

**Comment by aturner** [comment]
Thanks Mark.  Just to clarify: we want to *exclude* any records that have a non-UCSB URL.  So the Syracuse records shouldn't even get harvested.

**Comment by mredar** [comment]
I think ana is going to handle that but does it mean that ones with both URLs should be excluded? Who owns those objects?
