### ISSUE TITLE
CouchDB/Solr field additions: transcription, additional content to index and/or display?

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#84]
Proposed that we carve out additional new CouchDB fields (the first with a Solr analog):

1) Something in CouchDB (originalRecord/transcription) and Solr (transcription) to hold full-text transcriptions provided from a harvesting source
2) Something in CouchDB only to hold any additional content such as component-level titles or metadata (in the case of complex objects) provided from a harvesting source (e.g., originalRecord/components?)

Use cases:

1) We have a field in Nuxeo for transcriptions, that we could obtain through harvesting: ucldc_schema:transcription
2) UCSD has complex object component metadata and transcriptions, which they can surface in their Solr feed to us

**Comment by mredar** [comment]
Will pull transcription from originalRecord to solr index transcription.

Componensts will get dumped in "text" catchall field
