### ISSUE TITLE
Add mappings for UCI to isShownAt and isShownBy

### ISSUE THREAD

**Issue by aturner** [ucldc/harvester#90]
Add mappings from UCI's source metadata to isShownAt and isShownBy

See cells Q46-47 at https://docs.google.com/spreadsheets/d/1u2RE9PD0N9GkLQTFNJy3HiH9N5IbKDG52HjJ6JomC9I/edit#gid=265758929

For example, see this object:

1) CouchDB view:
https://54.84.142.143/couchdb/_utils/document.html?ucldc/26117--oai%3Aucispace-prod.lib.uci.edu%3A10575%2F100

2) UCI view:
http://ucispace.lib.uci.edu/handle/10575/100

3) UCI OAI-PMH output (search for http://ucispace.lib.uci.edu/handle/10575/100):
http://ucispace-prod.lib.uci.edu:8080/oai/request?verb=ListRecords&set=hdl_10575_7&metadataPrefix=oai_dc

This data in "dc:identifier" should map to isShownAt.  "didl:Resource@ref" should map to isShownBy.

**Comment by mredar** [comment]
Adrian,

Do we need to use a different metadataPrefix to get the didl data? This will take a bit of extra work if so.

Looks like the didl encapsulates the dc under it, with additional info

**Comment by aturner** [comment]
This should be the path to the value for isShownBy:

/metadata/didl:DIDL/didl:Item/didl:Component/didl:Resource@ref

**Comment by aturner** [comment]
<record> is the outermost wrapper, which bundles the <oai_dc...> data and the <didl...> data.

        <record>
            <header>
                <identifier>oai:ucispace-prod.lib.uci.edu:10575/25</identifier>
                <datestamp>2015-02-13T12:03:14Z</datestamp>
                <setSpec>hdl_10575_10</setSpec>
            </header>
            <metadata>
                <didl:DIDL xmlns:didl="urn:mpeg:mpeg21:2002:02-DIDL-NS"
                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                    xsi:schemaLocation="urn:mpeg:mpeg21:2002:02-DIDL-NS http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-21_schema_files/did/didl.xsd ">
                    <didl:DIDLInfo>
                        <dcterms:created xmlns:dcterms="http://purl.org/dc/terms/"
                            xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                            xsi:schemaLocation="http://purl.org/dc/terms/ "
                            >2015-02-14T00:28:51Z</dcterms:created>
                    </didl:DIDLInfo>
                    <didl:Item id="uuid-82840606-d74b-4526-b534-ed59816737fa">
                        <didl:Descriptor>
                            <didl:Statement mimeType="application/xml; charset=utf-8">
                                <dii:Identifier xmlns:dii="urn:mpeg:mpeg21:2002:01-DII-NS"
                                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                    xsi:schemaLocation="urn:mpeg:mpeg21:2002:01-DII-NS http://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-21_schema_files/dii/dii.xsd"
                                    >urn:hdl:10575/25</dii:Identifier>
                            </didl:Statement>
                        </didl:Descriptor>
                        <didl:Descriptor>
                            <didl:Statement mimeType="application/xml; charset=utf-8">
                                <oai_dc:dc
                                    xmlns:oai_dc="http://www.openarchives.org/OAI/2.0/oai_dc/"
                                    xmlns:dc="http://purl.org/dc/elements/1.1/"
                                    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                    xsi:schemaLocation="http://www.openarchives.org/OAI/2.0/oai_dc/ http://www.openarchives.org/OAI/2.0/oai_dc.xsd">
                                    <dc:title>Schedule of lectures</dc:title>
                                    <dc:creator>Rorty, Richard</dc:creator>
                                    <dc:subject>Rorty, Richard</dc:subject>
                                    <dc:description>Original file location on Richard Rorty's disk:
                                        MS-C017-FD032/!COLLOQU.IA</dc:description>
                                    <dc:description>File transferred from Richard Rorty's original
                                        floppy disk and converted to PDF for
                                        access.</dc:description>
                                    <dc:publisher>University of California, Irvine Libraries.
                                        Special Collections and Archives. Critical Theory Archive.
                                        Irvine, California 92623-9557. http://special.lib.uci.edu.
                                        email: spcoll@uci.edu</dc:publisher>
                                    <dc:date>2010-02-11T22:41:34Z</dc:date>
                                    <dc:type>Archives and Manuscripts</dc:type>
                                    <dc:format>application/pdf</dc:format>
                                    <dc:identifier>http://hdl.handle.net/10575/25</dc:identifier>
                                    <dc:language>en_US</dc:language>
                                    <dc:relation>Richard Rorty Papers. MS-C017. University of
                                        California, Irvine Libraries. Special Collections and
                                        Archives. Finding aid for entire collection available at:
                                        http://www.oac.cdlib.org/findaid/ark:/13030/kt9p3038mq/</dc:relation>
                                    <dc:rights>This material is provided for private study,
                                        scholarship, or research. Transmission or reproduction of
                                        any material protected by copyright beyond that allowed by
                                        fair use requires the written permission of the copyright
                                        owners. The authors or their heirs retain their copyrights
                                        to the material. Contact the University of California,
                                        Irvine Libraries, Special Collections and Archives for more
                                        information (spcoll@uci.edu).</dc:rights>
                                    <dc:rights>To access this item, interested researchers should
                                        submit an application online at
                                        http://special.lib.uci.edu/using/virtual-reading-room-application-form.html.
                                        Access may be granted in less than 5 business
                                        days.</dc:rights>
                                </oai_dc:dc>
                            </didl:Statement>
                        </didl:Descriptor>
                        <didl:Component id="uuid-1540587e-657b-4e39-ae84-943ef2364ba3">
                            <didl:Resource
                                ref="http://ucispace-prod.lib.uci.edu/xmlui/bitstream/10575/25/1/!COLLOQU.IA.pdf"
                                mimeType="application/pdf"/>
                        </didl:Component>
                    </didl:Item>
                </didl:DIDL>
            </metadata>
        </record>

**Comment by mredar** [comment]
There are access restrictions on the objects. I can't get at the isShownBy object, which looks to be pdfs for the Rorty one I'm using a test case.

**Comment by mredar** [comment]
they have type & format filled out in the metadata, will pull that into source resource.

**Comment by aturner** [comment]
Mark -- oops, re: isShownBy.  The Rorty and Poster collections will have PDFs that are not accessible, until a user registers through through UCI to access the content (it's open to any user, but they just need to register -- their "Virtual reading room").  So we won't be able to retrieve the actual files.

**Comment by mredar** [comment]
These are filled in, so we should be good for the UCI stuff.

**Comment by aturner** [comment]
Mark, I think UCI's DSpace stuff (OAI-PMH) is good to go -- you had fixed the harvesting code to address the main problem we identified
